#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TareaStoragePepsi
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MM1_PAL_COM")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertCLCHKIMG(CLCHKIMG instance);
    partial void UpdateCLCHKIMG(CLCHKIMG instance);
    partial void DeleteCLCHKIMG(CLCHKIMG instance);
    partial void InsertCLCHKTAR(CLCHKTAR instance);
    partial void UpdateCLCHKTAR(CLCHKTAR instance);
    partial void DeleteCLCHKTAR(CLCHKTAR instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::TareaStoragePepsi.Properties.Settings.Default.MM1_PAL_COMConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CLCHKIMG> CLCHKIMG
		{
			get
			{
				return this.GetTable<CLCHKIMG>();
			}
		}
		
		public System.Data.Linq.Table<CLCHKTAR> CLCHKTAR
		{
			get
			{
				return this.GetTable<CLCHKTAR>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CLCHKIMG")]
	public partial class CLCHKIMG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _CMCIAID;
		
		private decimal _CLCHKID;
		
		private decimal _CLCHKPROID;
		
		private decimal _CLCHKACTID;
		
		private int _CLCHKIMGLIN;
		
		private System.Data.Linq.Binary _CLCHKIMGBLOB;
		
		private System.Nullable<int> _CLCHKIMGSTORAGE;
		
		private System.Nullable<int> _CLCHKIMGSTS;
		
		private System.Nullable<int> _CLCHKIMGNAME;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCMCIAIDChanging(decimal value);
    partial void OnCMCIAIDChanged();
    partial void OnCLCHKIDChanging(decimal value);
    partial void OnCLCHKIDChanged();
    partial void OnCLCHKPROIDChanging(decimal value);
    partial void OnCLCHKPROIDChanged();
    partial void OnCLCHKACTIDChanging(decimal value);
    partial void OnCLCHKACTIDChanged();
    partial void OnCLCHKIMGLINChanging(int value);
    partial void OnCLCHKIMGLINChanged();
    partial void OnCLCHKIMGBLOBChanging(System.Data.Linq.Binary value);
    partial void OnCLCHKIMGBLOBChanged();
    partial void OnCLCHKIMGSTORAGEChanging(System.Nullable<int> value);
    partial void OnCLCHKIMGSTORAGEChanged();
    partial void OnCLCHKIMGSTSChanging(System.Nullable<int> value);
    partial void OnCLCHKIMGSTSChanged();
    partial void OnCLCHKIMGNAMEChanging(System.Nullable<int> value);
    partial void OnCLCHKIMGNAMEChanged();
    #endregion
		
		public CLCHKIMG()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMCIAID", DbType="Decimal(18,0) NOT NULL", IsPrimaryKey=true)]
		public decimal CMCIAID
		{
			get
			{
				return this._CMCIAID;
			}
			set
			{
				if ((this._CMCIAID != value))
				{
					this.OnCMCIAIDChanging(value);
					this.SendPropertyChanging();
					this._CMCIAID = value;
					this.SendPropertyChanged("CMCIAID");
					this.OnCMCIAIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLCHKID", DbType="Decimal(18,0) NOT NULL", IsPrimaryKey=true)]
		public decimal CLCHKID
		{
			get
			{
				return this._CLCHKID;
			}
			set
			{
				if ((this._CLCHKID != value))
				{
					this.OnCLCHKIDChanging(value);
					this.SendPropertyChanging();
					this._CLCHKID = value;
					this.SendPropertyChanged("CLCHKID");
					this.OnCLCHKIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLCHKPROID", DbType="Decimal(18,0) NOT NULL", IsPrimaryKey=true)]
		public decimal CLCHKPROID
		{
			get
			{
				return this._CLCHKPROID;
			}
			set
			{
				if ((this._CLCHKPROID != value))
				{
					this.OnCLCHKPROIDChanging(value);
					this.SendPropertyChanging();
					this._CLCHKPROID = value;
					this.SendPropertyChanged("CLCHKPROID");
					this.OnCLCHKPROIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLCHKACTID", DbType="Decimal(18,0) NOT NULL", IsPrimaryKey=true)]
		public decimal CLCHKACTID
		{
			get
			{
				return this._CLCHKACTID;
			}
			set
			{
				if ((this._CLCHKACTID != value))
				{
					this.OnCLCHKACTIDChanging(value);
					this.SendPropertyChanging();
					this._CLCHKACTID = value;
					this.SendPropertyChanged("CLCHKACTID");
					this.OnCLCHKACTIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLCHKIMGLIN", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int CLCHKIMGLIN
		{
			get
			{
				return this._CLCHKIMGLIN;
			}
			set
			{
				if ((this._CLCHKIMGLIN != value))
				{
					this.OnCLCHKIMGLINChanging(value);
					this.SendPropertyChanging();
					this._CLCHKIMGLIN = value;
					this.SendPropertyChanged("CLCHKIMGLIN");
					this.OnCLCHKIMGLINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLCHKIMGBLOB", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary CLCHKIMGBLOB
		{
			get
			{
				return this._CLCHKIMGBLOB;
			}
			set
			{
				if ((this._CLCHKIMGBLOB != value))
				{
					this.OnCLCHKIMGBLOBChanging(value);
					this.SendPropertyChanging();
					this._CLCHKIMGBLOB = value;
					this.SendPropertyChanged("CLCHKIMGBLOB");
					this.OnCLCHKIMGBLOBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLCHKIMGSTORAGE", DbType="Int")]
		public System.Nullable<int> CLCHKIMGSTORAGE
		{
			get
			{
				return this._CLCHKIMGSTORAGE;
			}
			set
			{
				if ((this._CLCHKIMGSTORAGE != value))
				{
					this.OnCLCHKIMGSTORAGEChanging(value);
					this.SendPropertyChanging();
					this._CLCHKIMGSTORAGE = value;
					this.SendPropertyChanged("CLCHKIMGSTORAGE");
					this.OnCLCHKIMGSTORAGEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLCHKIMGSTS", DbType="Int")]
		public System.Nullable<int> CLCHKIMGSTS
		{
			get
			{
				return this._CLCHKIMGSTS;
			}
			set
			{
				if ((this._CLCHKIMGSTS != value))
				{
					this.OnCLCHKIMGSTSChanging(value);
					this.SendPropertyChanging();
					this._CLCHKIMGSTS = value;
					this.SendPropertyChanged("CLCHKIMGSTS");
					this.OnCLCHKIMGSTSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLCHKIMGNAME", DbType="Int")]
		public System.Nullable<int> CLCHKIMGNAME
		{
			get
			{
				return this._CLCHKIMGNAME;
			}
			set
			{
				if ((this._CLCHKIMGNAME != value))
				{
					this.OnCLCHKIMGNAMEChanging(value);
					this.SendPropertyChanging();
					this._CLCHKIMGNAME = value;
					this.SendPropertyChanged("CLCHKIMGNAME");
					this.OnCLCHKIMGNAMEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CLCHKTAR")]
	public partial class CLCHKTAR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _CMCIAID;
		
		private decimal _CLCHKID;
		
		private decimal _CLCHKPROID;
		
		private decimal _CLCHKACTID;
		
		private int _CLCHKTARLIN;
		
		private decimal _CLCHKTARTPID;
		
		private decimal _CLCHKTARID;
		
		private string _CLCHKTARTXC;
		
		private string _CLCHKTARTXL;
		
		private string _CLCHKTARURL;
		
		private string _CLCHKTARNAME;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCMCIAIDChanging(decimal value);
    partial void OnCMCIAIDChanged();
    partial void OnCLCHKIDChanging(decimal value);
    partial void OnCLCHKIDChanged();
    partial void OnCLCHKPROIDChanging(decimal value);
    partial void OnCLCHKPROIDChanged();
    partial void OnCLCHKACTIDChanging(decimal value);
    partial void OnCLCHKACTIDChanged();
    partial void OnCLCHKTARLINChanging(int value);
    partial void OnCLCHKTARLINChanged();
    partial void OnCLCHKTARTPIDChanging(decimal value);
    partial void OnCLCHKTARTPIDChanged();
    partial void OnCLCHKTARIDChanging(decimal value);
    partial void OnCLCHKTARIDChanged();
    partial void OnCLCHKTARTXCChanging(string value);
    partial void OnCLCHKTARTXCChanged();
    partial void OnCLCHKTARTXLChanging(string value);
    partial void OnCLCHKTARTXLChanged();
    partial void OnCLCHKTARURLChanging(string value);
    partial void OnCLCHKTARURLChanged();
    partial void OnCLCHKTARNAMEChanging(string value);
    partial void OnCLCHKTARNAMEChanged();
    #endregion
		
		public CLCHKTAR()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMCIAID", DbType="Decimal(18,0) NOT NULL", IsPrimaryKey=true)]
		public decimal CMCIAID
		{
			get
			{
				return this._CMCIAID;
			}
			set
			{
				if ((this._CMCIAID != value))
				{
					this.OnCMCIAIDChanging(value);
					this.SendPropertyChanging();
					this._CMCIAID = value;
					this.SendPropertyChanged("CMCIAID");
					this.OnCMCIAIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLCHKID", DbType="Decimal(18,0) NOT NULL", IsPrimaryKey=true)]
		public decimal CLCHKID
		{
			get
			{
				return this._CLCHKID;
			}
			set
			{
				if ((this._CLCHKID != value))
				{
					this.OnCLCHKIDChanging(value);
					this.SendPropertyChanging();
					this._CLCHKID = value;
					this.SendPropertyChanged("CLCHKID");
					this.OnCLCHKIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLCHKPROID", DbType="Decimal(18,0) NOT NULL", IsPrimaryKey=true)]
		public decimal CLCHKPROID
		{
			get
			{
				return this._CLCHKPROID;
			}
			set
			{
				if ((this._CLCHKPROID != value))
				{
					this.OnCLCHKPROIDChanging(value);
					this.SendPropertyChanging();
					this._CLCHKPROID = value;
					this.SendPropertyChanged("CLCHKPROID");
					this.OnCLCHKPROIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLCHKACTID", DbType="Decimal(18,0) NOT NULL", IsPrimaryKey=true)]
		public decimal CLCHKACTID
		{
			get
			{
				return this._CLCHKACTID;
			}
			set
			{
				if ((this._CLCHKACTID != value))
				{
					this.OnCLCHKACTIDChanging(value);
					this.SendPropertyChanging();
					this._CLCHKACTID = value;
					this.SendPropertyChanged("CLCHKACTID");
					this.OnCLCHKACTIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLCHKTARLIN", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int CLCHKTARLIN
		{
			get
			{
				return this._CLCHKTARLIN;
			}
			set
			{
				if ((this._CLCHKTARLIN != value))
				{
					this.OnCLCHKTARLINChanging(value);
					this.SendPropertyChanging();
					this._CLCHKTARLIN = value;
					this.SendPropertyChanged("CLCHKTARLIN");
					this.OnCLCHKTARLINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLCHKTARTPID", DbType="Decimal(18,0) NOT NULL")]
		public decimal CLCHKTARTPID
		{
			get
			{
				return this._CLCHKTARTPID;
			}
			set
			{
				if ((this._CLCHKTARTPID != value))
				{
					this.OnCLCHKTARTPIDChanging(value);
					this.SendPropertyChanging();
					this._CLCHKTARTPID = value;
					this.SendPropertyChanged("CLCHKTARTPID");
					this.OnCLCHKTARTPIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLCHKTARID", DbType="Decimal(18,0) NOT NULL")]
		public decimal CLCHKTARID
		{
			get
			{
				return this._CLCHKTARID;
			}
			set
			{
				if ((this._CLCHKTARID != value))
				{
					this.OnCLCHKTARIDChanging(value);
					this.SendPropertyChanging();
					this._CLCHKTARID = value;
					this.SendPropertyChanged("CLCHKTARID");
					this.OnCLCHKTARIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLCHKTARTXC", DbType="VarChar(500)")]
		public string CLCHKTARTXC
		{
			get
			{
				return this._CLCHKTARTXC;
			}
			set
			{
				if ((this._CLCHKTARTXC != value))
				{
					this.OnCLCHKTARTXCChanging(value);
					this.SendPropertyChanging();
					this._CLCHKTARTXC = value;
					this.SendPropertyChanged("CLCHKTARTXC");
					this.OnCLCHKTARTXCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLCHKTARTXL", DbType="VarChar(50)")]
		public string CLCHKTARTXL
		{
			get
			{
				return this._CLCHKTARTXL;
			}
			set
			{
				if ((this._CLCHKTARTXL != value))
				{
					this.OnCLCHKTARTXLChanging(value);
					this.SendPropertyChanging();
					this._CLCHKTARTXL = value;
					this.SendPropertyChanged("CLCHKTARTXL");
					this.OnCLCHKTARTXLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLCHKTARURL", DbType="VarChar(50)")]
		public string CLCHKTARURL
		{
			get
			{
				return this._CLCHKTARURL;
			}
			set
			{
				if ((this._CLCHKTARURL != value))
				{
					this.OnCLCHKTARURLChanging(value);
					this.SendPropertyChanging();
					this._CLCHKTARURL = value;
					this.SendPropertyChanged("CLCHKTARURL");
					this.OnCLCHKTARURLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLCHKTARNAME", DbType="VarChar(500)")]
		public string CLCHKTARNAME
		{
			get
			{
				return this._CLCHKTARNAME;
			}
			set
			{
				if ((this._CLCHKTARNAME != value))
				{
					this.OnCLCHKTARNAMEChanging(value);
					this.SendPropertyChanging();
					this._CLCHKTARNAME = value;
					this.SendPropertyChanged("CLCHKTARNAME");
					this.OnCLCHKTARNAMEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
